# Generated by Django 4.2.1 on 2023-06-03 17:27

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ID_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('dni', models.TextField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Cliente registrado',
                'verbose_name_plural': 'Clientes registrados',
                'db_table': 'cliente',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('ID_local', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_local', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ubicacion geografica de nuestros locales',
                'verbose_name_plural': 'Locales',
                'db_table': 'Local',
            },
        ),
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('ID_auto', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.CharField(max_length=4)),
                ('alquiler_en_curso', models.BooleanField(default=False)),
                ('ID_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaAPI.locales')),
            ],
            options={
                'verbose_name': 'Auto disponible para alquiler',
                'verbose_name_plural': 'autos disponibles',
                'db_table': 'Auto',
            },
        ),
        migrations.CreateModel(
            name='Alquileres',
            fields=[
                ('Nro_nota', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alquiler', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('servicio', models.CharField(max_length=100)),
                ('en_curso', models.BooleanField(default=False)),
                ('ID_auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaAPI.autos')),
                ('ID_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ID_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaAPI.locales')),
            ],
            options={
                'verbose_name': 'Registro de alquileres',
                'verbose_name_plural': 'Alquileres',
                'db_table': 'Alquiler',
            },
        ),
    ]
