# Generated by Django 4.2.1 on 2023-05-22 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ID_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.TextField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cliente registrado',
                'verbose_name_plural': 'Clientes registrados',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('ID_local', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_local', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ubicacion geografica de nuestros locales',
                'verbose_name_plural': 'Locales',
                'db_table': 'Local',
            },
        ),
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('ID_auto', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.CharField(max_length=4)),
                ('alquiler_en_curso', models.IntegerField(default=-1)),
                ('ID_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaAPI.locales')),
            ],
            options={
                'verbose_name': 'Auto disponible para alquiler',
                'verbose_name_plural': 'autos disponibles',
                'db_table': 'Auto',
            },
        ),
        migrations.CreateModel(
            name='Alquileres',
            fields=[
                ('Nro_nota', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alquiler', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('servicio', models.CharField(max_length=100)),
                ('en_curso', models.BooleanField(default=True)),
                ('ID_auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaAPI.autos')),
                ('ID_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaAPI.clientes')),
                ('ID_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaAPI.locales')),
            ],
            options={
                'verbose_name': 'Registro de alquileres',
                'verbose_name_plural': 'Alquileres',
                'db_table': 'Alquiler',
            },
        ),
    ]
