# Generated by Django 4.2.1 on 2023-06-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservaAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fecha_nac',
        ),
    ]
