# Generated by Django 4.2.1 on 2023-06-03 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaAPI', '0002_remove_customuser_fecha_nac'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fecha_nac',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
