# Generated by Django 4.2.1 on 2023-06-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaAPI', '0004_autos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='locales',
            name='imagen',
            field=models.CharField(default='sin imagen', max_length=250),
            preserve_default=False,
        ),
    ]
