# Generated by Django 4.2.1 on 2023-06-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaAPI', '0005_locales_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='precioPorDia',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
            preserve_default=False,
        ),
    ]
