# Generated by Django 4.2.1 on 2023-06-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaAPI', '0006_autos_preciopordia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquileres',
            name='monto_cobrado',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
    ]
